### ISSUE TITLE
Add Asciidoctor Writing Day activities to the Writing Day page

### ISSUE THREAD

**Issue by briandominick** [DocOps/wtd2019#8]
Submit a brief writeup for the [Writing Day page](https://www.writethedocs.org/conf/portland/2019/writing-day/).

**Comment by briandominick** [comment]
Wrote draft for Alicia to edit and submit.

**Comment by diggerlilly** [comment]
Submitted a PR with edited content.
https://deploy-preview-902--dentist-canary-64055.netlify.com/conf/portland/2019/writing-day/

**Comment by briandominick** [comment]
Approved: https://github.com/writethedocs/www/pull/902
